version: "3.5"

services:

# https://hub.docker.com/_/memcached
  memcached:
    image: memcached:1.5-alpine

# https://hub.docker.com/_/rabbitmq
  rabbit:
    image: rabbitmq:3.7.8-management-alpine
    environment: 
      RABBITMQ_HIPE_COMPILE: 0
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

# https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0.13
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
        - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib

# https://hub.docker.com/_/nginx
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    environment: 
      NGINX_HOSTNAME: ${NGINX_HOSTNAME}
    ports: 
      - "${NGINX_PORT}:80"



  
#    build:
#      context: ./infrastructure/rabbit/
#      dockerfile: Dockerfile
#    environment:
#      DOMAIN:           ${DOMAIN}
#      LOOPS:            ${LOOPS}
#      NUM_THREADS:      ${NUM_THREADS}
#      PORT:             ${PORT}
#      PROTOCOL:         ${PROTOCOL}
#      RAMP_TIME:        ${RAMP_TIME}
#      TESTS:            ${TESTS}
#    secrets:
#      - source: aws_credentials
#        target: /jmeter/.aws
#        uid: '1000'
#        gid: '1000'
#        mode: 0440


volumes:
  db-data:  
