version: "3.5"

services:
  mysql:
    image: mysql:8.0.13
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
        - "${MYSQL_PORT}:3306"
    volumes:
      - ./infrastructure/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
